# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35401dfd3e8524dee3939c5023f3b9b8cc3c42e9e13655faddcde7b35d2371e510a703df4487d2965bfaae3ff37bd4f52bae37edc8235565c9332c0cf0b446fe

test:
  secret_key_base: ebd484f3d22a3e5d91723f43e937c5b7e3f2dd9346b5d74caeb574df7f8da4fbe7674c42d094388f3d56924f472574739d7bae85d32f96970ee8830a35adeedb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
